[ja]
  languageName = "Japanese"
  contentDir = "content/ja"
  weight = 1
  [ja.params]
    languageISO = "JA"
[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
